package br.com.banco.enums;

public enum TipoCodigoErro {
	VALOR_NAO_INFORMADO, //
	PELO_MENOS_UM, //
	VALOR_INVALIDO, //
	ERRO_INTERNO, //
	DADO_NAO_ENCONTRADO, //
	FORBIDDEN, //
	UNAUTHORIZED, //
	VIOLACAO_REGRA_DE_NEGOCIO, //
	NOT_FOUND
}
